### ISSUE TITLE
Project Plan: 05.03 ~ 05.09 

### ISSUE THREAD

**Issue by dodoongtak** [CodeSoom/HowMuchMore#142]
## 🤷‍♀️ 서비스 소개
꿈만 같은 아파트에 살려면 얼마나 많은 돈이 필요한지 확인 할 수 있습니다.

## 🙌 이번 주가 지나면 사용자가 사용 가능할 수 있는 새로운 기능은?
- 필요한 금액을 돈으로만 보는 것이 아닌 다른 가치있는 물질로도 파악 할 수 있습니다.
   - 주식 ( 삼성주, 테슬라)
   - 코인 ( 비트코인, 이더리움) 
   - 로또 당청금
- 아파트 위치를 지도로 확인 할 수 있습니다.
- 아파트 목록을 필터링 옵션을 선택해 정렬 할 수있습니다.

#### 아파트 구매에 필요한 금액을 
- [ ] 주식으로 치환하여 노출
- [ ] 코인으로 치환하여 노출
- [ ] 최근 로또 당첨금으로 치환하여 노출

#### 다음 지도
- [ ] 법정도 지번을 도로명 주소로 치환
- [ ] 아파트 위치 마크

#### 아파트 페이지 필터링 옵션
- [ ] 금액
- [ ] 건축년도

### FeedBacks | Feature Requests from Users

**Comment by dodoongtak** [comment]
### 05.03 ~ 05.09 Issues 

1. Proxy 서버 장애 발생
Free Server Host Heroku 특성 상 
request가 많아질 시 Proxy 서버가 차단되는 현상으로 
아파트 조회 불가. 

- 요청 시간이 길어질 시, 사용자는 요청이 실패했다는 메세지를 확인 할 수 있도록 조치해야된다. 

2. 스케줄 관리에 대한 미숙함
동시다발적으로 많은 일들을 하고 있는 와중에,
위의 명시된 기능들 구현이 우선순위가 뒤로 밀리는 상황에 직면

이번 주내 구현할 기능들을 리스트 할떄, 기능 갯수마다, 현재의 스케줄에 맞게 결정을 해야됀다라는 경험.

3. 위의 명시된 기능 이외 추가 된 기능
- 평당 가격
- Form Validation

21.05.16으로 연장.

기한을 1주가 아닌 2주로 산정.

**Comment by dodoongtak** [comment]
Issue: 아파트 카테고리 펜트하우스 및 랭킹 타입이 요청이 안되는 상황 발생.

Cause 1
국토교통부실거래 매매가 공공 데이터 자료에서, 
아파트 이름이 변경이 될 시 이전에 축적되었던 Data의 아파트명도 변경됨으로 원래 사용했던 아파트 키워드로 추출 할시 에러가발생. 

https://github.com/dodoongtak/how-much-more-server/commit/bc825387ecd9204e6195cd830ed3fdad642bf950

아파트 키워드 더펜트하우스청담 -> PH129로 변경하여 조치 완료.

**Comment by dodoongtak** [comment]
Issue: 아파트가격이 100억 이상으로 될 시에, 아파트 가격이 제대로 출력이 안되는 상황 (아파트 명: 더펜트하우스)

https://github.com/dodoongtak/how-much-more-server/commit/9513882637679b255ffe8419f48a0fa382f5dded

전처리 과정에서 하나의 comma만 제거 하는 로직을 모든 comma를 제거하는 로직으로 변경하여 조치 완료.

**Comment by dodoongtak** [comment]
Issue: Heroku에 무분별한 요청으로 인해 서버 다운 현상

https://github.com/dodoongtak/how-much-more-server/commit/9513882637679b255ffe8419f48a0fa382f5dded

CORS 설정하여, howmuchmore 도메인 이 외에서 따로 접근 방지 조치 완료. 

Error 🐛: domain 설정 시 'https'로 설정. SELF REVIEW를 유의하자 😢

**Comment by dodoongtak** [comment]
⚡ Enhancement

랜딩 페이지에서 한강 뷰 아파트 페이지로 밖에 이동하는 옵션만 제공하였기에, 
사용자가 다른 아파트 유형을 보지도 않은 결과를 GA에서 확인하였다.

#148 
랜딩페이지에서부터 선택 할 수 있는 아파트 유형을 제시하여, 폭 넓은 옵션을 제공하기로 조치. 

#147 
🔥 선호하지 않는 유형들은 과감하게 삭제 완료

**Comment by dodoongtak** [comment]
회사 관련 일정으로 인해 잠시 보류. 😭
